[package]
name = "ssh-agentctl"
version = "0.1.0"
edition = "2021"

[dependencies]
ssh-agent-client = { path = "../../lib/ssh-agent-client" } 
ssh-transport = { path = "../../lib/ssh-transport" } 

clap = { version = "4.5.16", features = ["derive"] }
eyre = "0.6.12"
tokio = { version = "1.39.3", features = ["full"] }
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
rpassword = "7.3.1"
sha2 = "0.10.8"
hex = "0.4.3"
pem = "3.0.4"
