[workspace]
members = [
    "fakesshd",
    "ssh",
    "sshdos",
    "ssh-connection",
    "ssh-protocol",
    "ssh-transport",
    "ssh-agent-client", "ssh-agentctl",
]
resolver = "2"

[workspace.dependencies]
tracing = "0.1.40"
