[package]
name = "fakessh"
version = "0.1.0"
edition = "2021"

[dependencies]
crypto-bigint = "0.5.5"
ed25519-dalek = "2.1.1"
eyre = "0.6.12"
rand = "0.8.5"
sha2 = "0.10.8"
tokio = { version = "1.39.2", features = ["full"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
x25519-dalek = "2.0.1"
