[package]
name = "sshdos"
version = "0.1.0"
edition = "2021"

[dependencies]
ssh-protocol = { path = "../../lib/ssh-protocol" }
ssh-transport = { path = "../../lib/ssh-transport" }
clap = { version = "4.5.15", features = ["derive"] }
eyre = "0.6.12"
rand = "0.8.5"
tokio = { version = "1.39.2", features = ["full"] }
tracing-subscriber = { version = "0.3.18", features = ["json", "env-filter"] }

tracing.workspace = true
rpassword = "7.3.1"
futures = "0.3.30"
