log_level = "info"


[subsystem.sftp]
# can also:
# path = "/nix/store/03fwrvyf4gw1gps9nmyvrxl17i7287ln-openssh-9.7p1/libexec/sftp-server"
path = "../../target/debug/cluelesshd-sftp-server"

[net]
ip = "0.0.0.0"
port = 2223

[auth]
host_keys = [
    # "/etc/ssh/ssh_host_ed25519_key",
    "./test_ed25519_key"
]
password_login = false
banner = "welcome to my server!!!\r\ni hope you enjoy your stay.\r\n"

[security]
unprivileged_uid = 355353
unprivileged_gid = 355353
#unprivileged_user = "sshd"
experimental_seccomp = true
