[package]
name = "ssh-agent-client"
version = "0.1.0"
edition = "2021"

[dependencies]
eyre = "0.6.12"
ssh-transport = { path = "../ssh-transport" }
tokio = { version = "1.39.3", features = ["net"] }
tracing.workspace = true
