[package]
name = "cluelessh-dos"
version = "0.1.0"
edition = "2021"

[dependencies]
cluelessh-protocol = { path = "../../lib/cluelessh-protocol" }
cluelessh-transport = { path = "../../lib/cluelessh-transport" }
clap = { version = "4.5.15", features = ["derive"] }
eyre.workspace = true
rand = "0.8.5"
tokio = { version = "1.39.2", features = ["full"] }
tracing-subscriber = { version = "0.3.18", features = ["json", "env-filter"] }

tracing.workspace = true
rpassword = "7.3.1"
futures = "0.3.30"

[lints]
workspace = true
